<html>
<head>
<title>Error</title>
<style>
body {
	font-family:Arial, Helvetica, sans-serif;
	font-size: 14px;
}
.error {
	border: 1px solid #FFCECE;
	padding: 5px 5px 5px 15px;
	background-color: #FFE5E5;
}
</style>
</head>
<body>

<h1>Oops!</h1>
<p>There was an error processing your request:</p>

<div class="error">
	<p><strong><?php echo $response->getError()->type ?>:</strong> <?php echo $response->getError()->message ?></p>
</div>
</body>
</html>