<h1>Introduction</h1>

<p>Web services are a great way to extend your application, however,
adding a Web API to an existing web application can be a tedious and
time-consuming task. Apify is a small web application that was developed
to ease that pain. It takes certain common patterns found in most web
services and abstract them so that you can quickly write Web APIs
without having to write too much code.</p>

<p><a href="http://www.youtube.com/watch?v=7ptoB0yCsDo" target="_blank">See
it in action (YouTube)</a></p>

<h1>Features</h1>

<ul>
	<li>Small and simple web application.</li>
	<li>Easy to install, easy to use and easy to extend.</li>
	<li>Powerful to satisfy most requirements.</li>
	<li>Works with any existing website (just unzip the files
	to your server and it's ready to use).</li>
	<li>Supports the following API styles: <a
		href="https://dev.twitter.com/docs/api" target="_blank">Twitter</a>, <a
		href="http://www.delicious.com/help/api" target="_blank">Delicious</a>,
	<a href="http://www.scribd.com/developers" target="_blank">Scribd</a>,
	<a href="http://upcoming.yahoo.com/services/api/" target="_blank">Upcoming</a>,
	<a href="http://zoom.it/pages/api/" target="_blank">Zoom.it</a>, and
	more.</li>
	<li>OOP-compliant architecture.</li>
	<li>Explicit Request and Response classes.</li>
	<li>RESTful URL mappings.</li>
	<li>Easy API versioning.</li>
	<li>Out of the box support for the following representations: JSON,
	XML, HTML.</li>
	<li>Content type negotiation.</li>
	<li>Encourages proper use of HTTP response codes.</li>
	<li>Domain models with out-of-the-box default implementations and input
	validation.</li>
</ul>
