<h1>Introduction</h1>

<p>Web services are a great way to extend your application, however,
adding a Web API to an existing web application can be a tedious and
time-consuming task. Apify is a small web application that was developed
to ease that pain. It takes certain common patterns found in most web
services and abstract them so that you can quickly write Web APIs
without having to write too much code.</p>

<p><a href="http://www.youtube.com/watch?v=7ptoB0yCsDo" target="_blank">See
it in action (YouTube)</a></p>

<h1>Features</h1>

<ul>
	<li>Small and simple web application.</li>
	<li>Easy to install, easy to use and easy to extend.</li>
	<li>Powerful to satisfy most requirements.</li>
	<li>Standalone. Works with any existing website (just unzip the files
	to your server and it's ready to use).</li>
	<li>Supports the following API styles: <a
		href="https://dev.twitter.com/docs/api" target="_blank">Twitter</a>, <a
		href="http://www.delicious.com/help/api" target="_blank">Delicious</a>,
	<a href="http://www.scribd.com/developers" target="_blank">Scribd</a>,
	<a href="http://upcoming.yahoo.com/services/api/" target="_blank">Upcoming</a>,
	<a href="http://zoom.it/pages/api/" target="_blank">Zoom.it</a>, and
	more.</li>

	<li>OOP-compliant architecture.</li>
	<li>Explicit Request and Response classes.</li>
	<li>RESTful URL mappings.</li>
	<li>Easy API versioning.</li>
	<li>Out of the box support for the following representations: JSON,
	XML, HTML.</li>
	<li>Content type negotiation.</li>

	<li>Encourages proper use of HTTP response codes.</li>
	<li>Domain models with out-of-the-box default implementations and input
	validation.</li>
</ul>

<h1>Requirements</h1>
<ul>
	<li>PHP 5.2 or greater.</li>
	<li>MySQL and PDO_MYSQL driver (optional).</li>

</ul>


<h1>Debugging</h1>

<p>The debugger is enabled by default. You can always turn it off by
setting the "debug" option to false in the config.php file.</p>

<h1>Reporting bugs</h1>

<p>We use <a href="https://github.com/apify/apify-library/issues"
	target="_blank">GitHub</a> as issue tracker. Bug reports are incredibly
helpful, so take time to report bugs and request features in our ticket
tracker. Thank you!</p>

<h1>Contributing</h1>

<p>The best ways to contribute are by finding and reporting bugs,
writing tests for bugs, and improving the documentation. We're always
grateful for patches to Apify's code. If you want to change the code, be
careful follow our design-decisions. Be especially careful not to
increase complexity if you don't have a really good reason.
<p>
<h1>Contact</h1>

<ul>
	<li>If you encounter any problems, please use the <a
		href="https://github.com/apify/apify-library/issues" target="_blank">GitHub
	issue tracker</a>.</li>
	<li>For updates follow <a href="https://twitter.com/fedecarg"
		target="_blank">@fedecarg</a> on Twitter.</li>
</ul>

<h1>License</h1>
<ul>
	<li>Copyright (c) 2011, <a href="http://www.kewnode.com">Kewnode Ltd.</a>
	All rights reserved.</li>
</ul>