<h2>Users</h2>

<table>
    <thead>
      <tr>
        <th>#</th>
        <th>Username</th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($view->users as $user): ?>
      <tr>
        <td><?php echo $user->id ?></td>
        <td><?php echo $user->username ?></td>
        <td><?php echo $user->name ?></td>
        <td><?php echo $user->email ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
</table>