<h1>Users</h1>

<table>
    <tbody>
        <tr>
            <td><strong>ID</strong></td>
            <td><strong>Username</strong></td>
            <td><strong>Name</strong></td>
            <td><strong>Email</strong></td>
        </tr>
        <?php foreach ($view->users as $user): ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->username ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $user->email ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

