<h2>User</h2>

<table>
    <thead>
      <tr>
        <th>#</th>
        <th>Username</th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <?php if (isset($view->user)): ?>
      <tr>
        <td><?php echo $view->user->id ?></td>
        <td><?php echo $view->user->username ?></td>
        <td><?php echo $view->user->name ?></td>
        <td><?php echo $view->user->email ?></td>
      </tr>
    <?php endif; ?>
    </tbody>
</table>
