<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<title>Apify - Error</title>
<style>
body {
    font-family:Arial, Helvetica, sans-serif;
    font-size: 14px;
}
.error {
    border: 1px solid #FFCECE;
    padding: 5px 5px 5px 15px;
    background-color: #FFE5E5;
}
.info {
    padding: 5px;
    border: 1px solid #e8e8e8;
    background-color: #f4f4f4;
}

</style>
</head>

<body>

<div id="main">
    <?php echo $view->layout()->content; ?>
</div>

</body>
</html>
